compose is entirely vibecoded (read for proof)
This reverts commit 6cbb8536f0c52990bb4d64864232fba70dc4623a.

the login screen with cmp alpha02 will crash with this

java.lang.AbstractMethodError: abstract method "void androidx.compose.foundation.style.CustomStyle.applyStyle(androidx.compose.foundation.style.CustomStyleScope)" on receiver java.lang.Class<androidx.compose.material3.OutlinedTextFieldDefaults$$ExternalSyntheticLambda0>

i wanted to update to alpha02 as it removed the need for PlatformContext.clickSound but now i've wasted a bunch of time removing usages of it for no reason because of this crash

I know it's an alpha but surely they would check to see if a single composable would crash the entire app??? is there no code review or unit tests? idgi

# Conflicts:
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/common/ErrorCodeBlock.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/dialogs/SideloadingDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/layouts/ArtCarousel.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/layouts/HorizontalSection.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/layouts/MiniPlayer.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/layouts/NestedTopBar.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/layouts/RootTopBar.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/sheets/CollectionSheet.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/sheets/SleepTimerSheet.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/sheets/SongSheet.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/components/sheets/SortSheet.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/album/components/Item.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/album/components/SortButton.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/collection/components/HeadingRow.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/collection/components/HeadingRowButtons.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/login/pages/SuggestionChips.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/nowPlaying/components/controls/MoreButton.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/nowPlaying/components/controls/StarButton.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/playlist/PlaylistListScreen.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/playlist/components/Item.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/playlist/components/SortButton.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/playlist/dialogs/PlaylistUpdateDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/queue/QueueScreen.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/radio/RadioListScreen.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/radio/components/Card.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/radio/dialogs/RadioCreateDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/search/SearchScreen.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/search/components/Chips.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/search/components/TopBar.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/FontsScreen.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/dialogs/GridSizeDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/dialogs/LyricsPriorityDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/dialogs/NavtabsDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/dialogs/NowPlayingSliderStyleDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/settings/dialogs/ThemeDialog.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/share/components/Item.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/song/components/SortButton.kt
#	composeApp/src/commonMain/kotlin/paige/navic/ui/screens/starred/components/Content.kt